### ISSUE TITLE
Add ability to change the default font

### ISSUE THREAD

**Issue by ahmaduxui** [umairayub79/SayadGanj-Desktop#1]
Ability to change the default font

Open Source Fonts:
[Estedad](https://github.com/aminabedi68/Estedad)
[Vazirmatn](https://github.com/rastikerdar/vazirmatn)

**Comment by umairayub79** [comment]
Noted

**Comment by umairayub79** [comment]
Done!

**Comment by umairayub79** [comment]
Done
